// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_name_property_to_MembershipType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_name_property_to_MembershipType));
        
        string IMigrationMetadata.Id
        {
            get { return "201807150048040_add_name_property_to_MembershipType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
